services:
  puppeteer:
    image: browserless/chrome:latest
    restart: unless-stopped
    shm_size: '1gb'
    environment:
      - "CONNECTION_TIMEOUT=300000"
    ports:
      - "3010:3000"
  pzo-online-app:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '1gb'
    ports:
      - "3999:3000"
    env_file:
      - .env
    environment:
      PUPPETEER_WS_ENDPOINT: ws://puppeteer:3000
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
#      DEBUG: puppeteer:*
